name: Deploy FTP

on:
  push:
    branches:
      - main

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar código
        uses: actions/checkout@v6

      - name: Instalar lftp
        run: sudo apt-get update && sudo apt-get install -y lftp

      - name: Subir archivos por FTPS
        env:
          FTP_SERVER: ${{ secrets.FTP_SERVER }}
          FTP_USER: ${{ secrets.FTP_USER }}
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}

        run: |
          lftp -c "
          set ftp:ssl-force true;
          set ftp:ssl-protect-data true;
          set ssl:verify-certificate no;
          set ftp:passive-mode true;

          open -u \"$FTP_USER\",\"$FTP_PASSWORD\" \"$FTP_SERVER\";

          mirror --reverse \
            --verbose \
            --delete \
            --exclude-glob .git/** \
            --exclude-glob .github/** \
            ./ /public_html/;
          "